<?php

namespace backend\controllers;

use backend\models\ReportDev;

use common\controllers\BaseController;

class ReportDevController extends BaseController
{
    public $modelClass = ReportDev::class;

    public $indexTemplate  = 'index';
    public $viewTemplate   = 'view';
    public $createTemplate = 'edit';
    public $editTemplate   = 'edit';

    public function beforeAction($action)
    {
        ReportDev::createView();
        return parent::beforeAction($action); // TODO: Change the autogenerated stub

    }
}
